### ISSUE TITLE
SERVICE_DELAYED_AUTO_START_INFO uses bool instead of BOOL

### ISSUE THREAD

**Issue by ksubrama** [djberg96/win32-service#27]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685155(v=vs.85).aspx

BOOL is a 4-byte value on both 32 and 64-bit windows.

https://github.com/djberg96/win32-service/commit/3d3abac42440ad1926319f3b5f69d14ce00bb2a9 was the change that introduced the break.  It is a cosmetic change but calls to:
```
Service.configure(:service_name => 'foo', :delayed_start => true)
```
now return 
```
SystemCallError:
  The parameter is incorrect. - ChangeServiceConfig2: The parameter is incorrect.
```

**Comment by djberg96** [comment]
Oh, bloody hell.

http://blogs.msdn.com/b/oldnewthing/archive/2004/12/22/329884.aspx

**Comment by djberg96** [comment]
The confusing thing is that it works out alright to do that on return types. Definitely something to watch out for. I may have to check the rest of the code now. Thanks for the report.

**Comment by djberg96** [comment]
I think what I'll do is allow both 1/0 and true/false, and just convert it on the fly, rather than undoing the whole commit. I think I could modify the FFI struct, actually.

**Comment by ksubrama** [comment]
:) I actually thought of that exact blog post.  And I've made the exact same mistake before as well :)  I managed to run into it with even more hilarity.  You can even dodge the issue in arguments if you have a struct and you have a bool followed by some int/int64 because the alignment rules, together with little-endianness of x86 will make sure that it works out.  It's only when it's at the tail end of a struct do you run into an error.  It's thoroughly insidious.

**Comment by djberg96** [comment]
@ksubrama How's this? https://github.com/djberg96/win32-service/pull/28

**Comment by djberg96** [comment]
Ok, released 0.8.7. Hope I didn't break too much code out there. ;)

**Comment by ksubrama** [comment]
<3

**Comment by djberg96** [comment]
@ksubrama I actually modified the original PR because of an issue, so the final code should work better. Let me know if you have any issues.
