### ISSUE TITLE
Service_Main thread exited still occurs 

### ISSUE THREAD

**Issue by commel** [djberg96/win32-service#30]
This is the same problem here as #4 with JRuby 1.7.22 (ignore the path, thats nasty i know) and Oracle Java 1.8.0_60 on a Windows Server 2008R2 (all 64 bit). Using win32-service 0.8.7.

```ruby
F, [2015-09-08T13:21:42.017000 #2768] FATAL -- : Service_Main thread exited abnormally (RuntimeError)
C:/Program Files/xxxx/jruby-1.7.20.1/lib/ruby/gems/shared/gems/win32-service-0.8.7/lib/win32/daemon.rb:282:in `mainloop'
C:/Program Files/xxxx/jruby-1.7.20.1/lib/ruby/gems/shared/gems/win32-service-0.8.7/lib/win32/daemon.rb:217:in `mainloop'
client.rb:43:in `(root)'
```

Despite @Insnood's problem this is running locally. We could really need some help here, please!

**Comment by djberg96** [comment]
Have you tried with more recent versions of JRuby?

**Comment by djberg96** [comment]
@commel I released 0.8.8 today that had some function prototype fixes. I don't know if it will fix your issue, but it's worth a shot.

**Comment by djberg96** [comment]
I ran it the demo daemon without incident using JRuby 9.1.1.0 on Windows 8. Closing for now.

**Comment by fmoyses** [comment]
Hi @djberg96!

We're facing this problem with JRuby 9.1.2.0 and 0.8.9 version.
It's a Windows Server 2012 R2 server with JRE 1.80_102 (all 64-bit).
We have the same service running in other servers.

Do you know any way we could debug it to get a more meaningful error?

Service_Main thread exited abnormally
RuntimeError: Service_Main thread exited abnormally
  mainloop at C:/jruby-9.1.2.0/lib/ruby/gems/shared/gems/win32-service-0.8.9/lib/win32/daemon.rb:279
  mainloop at C:/jruby-9.1.2.0/lib/ruby/gems/shared/gems/win32-service-0.8.9/lib/win32/daemon.rb:214
     <top> at service.rb:28

**Comment by djberg96** [comment]
@fmoyses The typical approach I use is to wrap the entire Daemon in a begin/rescue and log any errors to a file to see if I can smoke out the problem.

**Comment by fmoyses** [comment]
@djberg96  I believe we are doing that and something is happening before actually calling service_main. I've even put a log before actually running our service, but the `log "testing"` isn't registered.

`
require 'rubygems'
require 'win32/daemon'
require 'handit-wiki/server'

include Win32

class WikiDaemon < Daemon
  def service_main
	begin
                log "testing"
		HanditWiki.new.run ARGV[0]
	rescue Exception => e
		log e.message
	end
  end

  def service_stop
	exit 0
  end
  
  def log(text)
    File.open('c:\\Handit\\logs\log-service-wiki.txt', 'a') { |f| f.puts "#{Time.now}: #{text}" }
  end


end

begin
	WikiDaemon.mainloop
rescue Exception => e
	puts "#{e.message}"
	File.open('c:\\Handit\\logs\log-service-wiki.txt', 'a') { |f| f.puts "#{Time.now}: #{e.message}" } 
	raise
end
`

**Comment by djberg96** [comment]
@fmoyses Try wrapping the Daemon itself:

    begin
       class WikiDaemon
       # ...
       end
    rescue Exception =>
       # put logging here
    end
