### ISSUE TITLE
Is this only able to manage 32-bit services?

### ISSUE THREAD

**Issue by zrisher** [djberg96/win32-service#31]
From the name of this repo I assume it is only able to manage 32-bit services, but I don't see that in the documentation. Is that a correct assumption? Or could I have a separately created 64-bit process that I can start/stop with this library?

**Comment by djberg96** [comment]
It should work fine with 64-bit processes. The "win32" is just a generic reference to the Windows API that was used prior to the existence of 64-bit Windows. Don't read too much into it. :)

**Comment by zrisher** [comment]
Awesome, thank you!
