### ISSUE TITLE
Windows XP isn't supported?

### ISSUE THREAD

**Issue by PerpetuumMobile** [djberg96/win32-service#33]
OS: Windows XP Professional
Ruby: Rubyinstaller 2.0.0
Gems installed: fxruby, win32-service

Code:
```
def os_windows?
  /cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM
end

if os_windows? then
  require 'win32/service'
  include Win32
  require 'win32/daemon'

  Service.services do |service|
    puts service.service_name
  end
else
  
end

p RUBY_PLATFORM
```

Output:

> C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-service-0.8.7/lib/win32/windows/helper.rb:36:in `raise_windows_error': Invalid level. - QueryServiceConfig2:  (SystemCallError)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-service-0.8.7/lib/win32/service.rb:1380:in `get_config2_info'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-service-0.8.7/lib/win32/service.rb:1092:in `block in services'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-service-0.8.7/lib/win32/service.rb:1037:in `upto'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-service-0.8.7/lib/win32/service.rb:1037:in `services'
        from helloworld.rb:23:in `<main>'

At Windows 7 there is no error, service list is printed out correctly.

**Comment by djberg96** [comment]
No, support for Windows XP was dropped when MS dropped it.

**Comment by PerpetuumMobile** [comment]
Ok, thnx for the info, I'll use https://github.com/Iristyle/win32-service/tree/restore_win_2003_compat, it works in both new and old Windows systems.
