### ISSUE TITLE
Setting service Recovery options

### ISSUE THREAD

**Issue by vais** [djberg96/win32-service#36]
Windows Services have a feature called *Recovery*, whereby you can specify actions to take on First, Second, and Subsequent failures. Is there any way to set these options when creating a service?

![clipboard01](https://cloud.githubusercontent.com/assets/77592/23649303/9da501f2-0350-11e7-9f14-23e35bf6b3f1.png)

Thanks in advance for any pointers...

**Comment by djberg96** [comment]
@vais Look for `:failure_actions`.

**Comment by vais** [comment]
@djberg96 thank you! Just to clarify, you don't mean this option is documented somewhere, you mean *search the source code for the string "failure_actions"*, right? (Which is what I did, and there's quite a bit there for me to play with once I get back in my Windows machine, so, thanks again for pointing me in this direction regardless).

**Comment by djberg96** [comment]
@vais I didn't document every option, there are so many, sorry. This project could probably use some love on the wiki, with screenshots like yours that line up with the various options.

**Comment by vais** [comment]
Totally understand and 👍 

On a little different but related subject, before diving in from the deep end, I was playing with setting Recovery options manually, via the Windows Services user interface, and it looks like Windows does not recognize Ruby process exiting due to an unhandled exception as a "crash", so it does not restart the service (does not attempt any recovery actions). With the same Recovery options, killing the process in Task Manager *is* recognized as a "crash", and the service is restarted.

Have you had any luck getting this to work? As far as I know, if there is an unhandled exception, Ruby will exit with a non-zero exit code, which, as far as I know, is what Windows uses to decide whether the service "crashed". What am I missing?

My apologies in advance for opportunistically picking your brain 🙇

**Comment by djberg96** [comment]
@vais I've never really tinkered with that option, so I'm not sure how to handle forcing Windows to interpret a Ruby interpreter exception as a crash.

@phasis68 Any thoughts?

**Comment by djberg96** [comment]
@vais For what it's worth, I found this article that discusses it a bit:

https://mdenomy.wordpress.com/2008/02/28/using-the-automatic-recovery-features-of-windows-services/

**Comment by djberg96** [comment]
@vais Thanks for digging into that. I'll add something to the wiki about it.

**Comment by djberg96** [comment]
@vais How does this look?

https://github.com/djberg96/win32-service/wiki/Daemons-and-Exception-Handling#tip-2---dealing-with-recovery-options

**Comment by vais** [comment]
@djberg96 it helps, thank you for taking the time to write this up!
