### ISSUE TITLE
Compability for 1.9.x

### ISSUE THREAD

**Issue by mikevoets** [djberg96/win32-service#38]
I cannot install win32-service with Ruby 1.9.3, I get the following error:

ERROR: Error installing win32-service:
               ffi requires Ruby version < 2.5, >= 2.0

**Comment by djberg96** [comment]
There's nothing I can do if FFI requires Ruby 2.x. And frankly, you should not be using Ruby 1.9.x at this point.

**Comment by mikevoets** [comment]
Any idea what version if FFI win32-service is using? I only see versions of FFI that require max 1.8.

**Comment by djberg96** [comment]
win32-service doesn't specify a version requirement for FFI. If FFI only requires 1.8, then I don't know why you're getting that error. What version of Rubygems are you running?

**Comment by mikevoets** [comment]
This can be closed.
